/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <string.h>
#include "GPIO_driver.h"
#include "UART_driver.h"
#include "RCC_driver.h"
#include "bsp.h"


int main(void){
	uint8_t s1[] = "Mahmoud Fawzi\n";
	uint8_t s2[] = "Salah Ahmed\n";
	uint8_t data1[] = "Le Old\n";
	uint8_t data2[] = "Le Shungus\n";
	uint8_t data_size;
	USART_Handle_t test;
	test.pUSARTx = USART1;
	test.USART_Config.USART_Baud = USART_STD_BAUD_115200;
	test.USART_Config.USART_NoOfStopBits = USART_STOPBITS_1;
	test.USART_Config.USART_ParityControl = USART_PARITY_DISABLE;
	test.USART_Config.USART_Mode = USART_MODE_TXRX;
	test.USART_Config.USART_WordLength = USART_WORDLEN_8BITS;
	USART_Init(&test);

	  /*configuring the LED*/
	  GPIO_Handle_t GPIOLed;
	  GPIOLed.pGPIOx = GPIOA;
	  GPIOLed.GPIO_PinConfig.GPIO_PinNumber =  GPIO_PIN_NO_5;
	  GPIOLed.GPIO_PinConfig.GPIO_PinMode   =  GPIO_MODE_OUT;
	  GPIOLed.GPIO_PinConfig.GPIO_PinSpeed  =  GPIO_SPEED_FAST;
	  GPIOLed.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	  GPIOLed.GPIO_PinConfig.GPIO_PinPuPdControl  = GPIO_NO_PUPD;
	  GPIO_CLKCNT(GPIOA,ENABLE);
	  GPIO_Init(&GPIOLed);


	USART_GPIOInit(GPIOA,GPIO_PIN_NO_9,7);  /*TX*/
	USART_GPIOInit(GPIOA,GPIO_PIN_NO_10,7);  /*RX*/
	while(1){
		USART_ReceiveData(&test, &data_size, 1);  /*first byte will contain data length*/
		uint8_t data[data_size];
		USART_ReceiveData(&test, data, sizeof(data));
		uint8_t result = strcmp(data,s1);
		switch(result){
		case(0):
				USART_SendData(&test, data1, sizeof(data1));
				break;
		case(1):
				USART_SendData(&test, data2, sizeof(data2));
				break;
		}
		GPIO_ToggleOutputPin(GPIOA,GPIO_PIN_NO_5);
	}
}
