/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

uint8_t a[4] = {0xAA, 0xAA, 0xAA, 0xAA};
const uint8_t b[4] ={0xBB,0xBB,0xBB,0xBB};
uint8_t c[4];

int main(void)
{
	uint8_t d[4] = {0x01,0x02,0x03,0x04};
	static uint8_t e[4] = {0xFF,0xFF,0xFF,0xFF};
	static uint8_t f[4];
	uint8_t sum = 0;
	for(int i = 0; i < 5; i++){
		sum += a[i] + b[i] + c[i] + d[i] + e[i];
	}

	for(int j = 0; j < 5; j++){
		f[j] += sum;
	}
}
